<?php
/**
 * DefaultApi
 * PHP version 7.4
 *
 * @category Class
 * @package  StillfrontPaymentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shop
 *
 * Shop
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StillfrontPaymentApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use StillfrontPaymentApi\ApiException;
use StillfrontPaymentApi\Configuration;
use StillfrontPaymentApi\HeaderSelector;
use StillfrontPaymentApi\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  StillfrontPaymentApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getApiV2CatalogIndex' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getApiV2CatalogIndex
     *
     * @param  int $game_id game_id (required)
     * @param  int $network_id network_id (required)
     * @param  int $instance_id instance_id (required)
     * @param  int $player_id player_id (required)
     * @param  string $remote_address remote_address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV2CatalogIndex'] to see the possible values for this operation
     *
     * @throws \StillfrontPaymentApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response
     */
    public function getApiV2CatalogIndex($game_id, $network_id, $instance_id, $player_id, $remote_address, string $contentType = self::contentTypes['getApiV2CatalogIndex'][0])
    {
        list($response) = $this->getApiV2CatalogIndexWithHttpInfo($game_id, $network_id, $instance_id, $player_id, $remote_address, $contentType);
        return $response;
    }

    /**
     * Operation getApiV2CatalogIndexWithHttpInfo
     *
     * @param  int $game_id (required)
     * @param  int $network_id (required)
     * @param  int $instance_id (required)
     * @param  int $player_id (required)
     * @param  string $remote_address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV2CatalogIndex'] to see the possible values for this operation
     *
     * @throws \StillfrontPaymentApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getApiV2CatalogIndexWithHttpInfo($game_id, $network_id, $instance_id, $player_id, $remote_address, string $contentType = self::contentTypes['getApiV2CatalogIndex'][0])
    {
        $request = $this->getApiV2CatalogIndexRequest($game_id, $network_id, $instance_id, $player_id, $remote_address, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getApiV2CatalogIndexAsync
     *
     * @param  int $game_id (required)
     * @param  int $network_id (required)
     * @param  int $instance_id (required)
     * @param  int $player_id (required)
     * @param  string $remote_address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV2CatalogIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getApiV2CatalogIndexAsync($game_id, $network_id, $instance_id, $player_id, $remote_address, string $contentType = self::contentTypes['getApiV2CatalogIndex'][0])
    {
        return $this->getApiV2CatalogIndexAsyncWithHttpInfo($game_id, $network_id, $instance_id, $player_id, $remote_address, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getApiV2CatalogIndexAsyncWithHttpInfo
     *
     * @param  int $game_id (required)
     * @param  int $network_id (required)
     * @param  int $instance_id (required)
     * @param  int $player_id (required)
     * @param  string $remote_address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV2CatalogIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getApiV2CatalogIndexAsyncWithHttpInfo($game_id, $network_id, $instance_id, $player_id, $remote_address, string $contentType = self::contentTypes['getApiV2CatalogIndex'][0])
    {
        $returnType = '\StillfrontPaymentApi\Model\GetApiV2CatalogIndex200Response';
        $request = $this->getApiV2CatalogIndexRequest($game_id, $network_id, $instance_id, $player_id, $remote_address, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getApiV2CatalogIndex'
     *
     * @param  int $game_id (required)
     * @param  int $network_id (required)
     * @param  int $instance_id (required)
     * @param  int $player_id (required)
     * @param  string $remote_address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApiV2CatalogIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getApiV2CatalogIndexRequest($game_id, $network_id, $instance_id, $player_id, $remote_address, string $contentType = self::contentTypes['getApiV2CatalogIndex'][0])
    {

        // verify the required parameter 'game_id' is set
        if ($game_id === null || (is_array($game_id) && count($game_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $game_id when calling getApiV2CatalogIndex'
            );
        }

        // verify the required parameter 'network_id' is set
        if ($network_id === null || (is_array($network_id) && count($network_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $network_id when calling getApiV2CatalogIndex'
            );
        }

        // verify the required parameter 'instance_id' is set
        if ($instance_id === null || (is_array($instance_id) && count($instance_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instance_id when calling getApiV2CatalogIndex'
            );
        }

        // verify the required parameter 'player_id' is set
        if ($player_id === null || (is_array($player_id) && count($player_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $player_id when calling getApiV2CatalogIndex'
            );
        }

        // verify the required parameter 'remote_address' is set
        if ($remote_address === null || (is_array($remote_address) && count($remote_address) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $remote_address when calling getApiV2CatalogIndex'
            );
        }


        $resourcePath = '/catalog';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $game_id,
            'gameId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $network_id,
            'networkId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $instance_id,
            'instanceId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $player_id,
            'playerId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $remote_address,
            'remoteAddress', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
